# Generated by Django 5.2.14 on 2026-05-07 23:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Должность')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('code', models.SlugField(help_text='Например: dominex, finsoft, ssod_lk', max_length=80, unique=True, verbose_name='Код продукта')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='Отчество')),
                ('access_class', models.CharField(choices=[('S', 'S — системный'), ('A', 'A — суперадмин'), ('B', 'B — высокий'), ('C', 'C — расширенный'), ('D', 'D — средний'), ('E', 'E — ограниченный'), ('F', 'F — минимальный служебный'), ('G', 'G — базовый пользователь')], default='G', max_length=1, verbose_name='Класс доступа')),
                ('must_change_password', models.BooleanField(default=True, verbose_name='Требуется смена пароля')),
                ('blocked_reason', models.TextField(blank=True, verbose_name='Причина блокировки')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.organization', verbose_name='Организация')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['last_name', 'first_name', 'username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('event_type', models.CharField(choices=[('login_success', 'Успешный вход'), ('login_failed', 'Неуспешный вход'), ('logout', 'Выход'), ('key_login_success', 'Вход по ключу успешен'), ('key_login_failed', 'Вход по ключу неуспешен'), ('access_denied', 'Доступ запрещен'), ('access_granted', 'Доступ разрешен')], max_length=50, verbose_name='Тип события')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Детали события')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Событие авторизации',
                'verbose_name_plural': 'События авторизации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('code', models.CharField(max_length=150, verbose_name='Код права')),
                ('name', models.CharField(max_length=255, verbose_name='Название права')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='accounts.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Право продукта',
                'verbose_name_plural': 'Права продуктов',
                'ordering': ['product__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ProductRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('code', models.SlugField(max_length=100, verbose_name='Код роли')),
                ('name', models.CharField(max_length=255, verbose_name='Название роли')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='accounts.productpermission', verbose_name='Права')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='accounts.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Роль продукта',
                'verbose_name_plural': 'Роли продуктов',
                'ordering': ['product__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SSODAccessKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(help_text='Например: Ноутбук Владимира, Рабочий ПК, Тестовый ключ', max_length=255, verbose_name='Название ключа')),
                ('fingerprint_sha256', models.CharField(max_length=128, unique=True, verbose_name='SHA256 fingerprint')),
                ('public_key_pem', models.TextField(blank=True, verbose_name='Публичный ключ PEM')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('revoked', 'Отозван'), ('expired', 'Истек'), ('lost', 'Утерян')], default='active', max_length=20, verbose_name='Статус')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата выпуска')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отзыва')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее использование')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssod_keys', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ключ доступа ССОД',
                'verbose_name_plural': 'Ключи доступа ССОД',
                'ordering': ['user', '-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('email_type', models.CharField(choices=[('work', 'Рабочая'), ('personal', 'Личная'), ('other', 'Другая')], default='work', max_length=20, verbose_name='Тип почты')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основная')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Email пользователя',
                'verbose_name_plural': 'Email пользователей',
                'ordering': ['user', '-is_primary', 'email'],
            },
        ),
        migrations.CreateModel(
            name='UserMessenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('messenger_type', models.CharField(choices=[('telegram', 'Telegram'), ('matrix', 'Matrix'), ('compass', 'Compass'), ('other', 'Другой')], default='telegram', max_length=30, verbose_name='Тип мессенджера')),
                ('identifier', models.CharField(max_length=255, verbose_name='Идентификатор')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messengers', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Мессенджер пользователя',
                'verbose_name_plural': 'Мессенджеры пользователей',
                'ordering': ['user', '-is_primary', 'messenger_type'],
            },
        ),
        migrations.CreateModel(
            name='UserPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('phone_type', models.CharField(choices=[('work', 'Рабочий'), ('mobile', 'Мобильный'), ('other', 'Другой')], default='work', max_length=20, verbose_name='Тип телефона')),
                ('country_code', models.CharField(default='+7', max_length=8, verbose_name='Код страны')),
                ('number', models.CharField(help_text='Формат: XXX-XXX-XXXX', max_length=12, validators=[django.core.validators.RegexValidator(message='Номер должен быть в формате XXX-XXX-XXXX', regex='^\\d{3}-\\d{3}-\\d{4}$')], verbose_name='Номер')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Телефон пользователя',
                'verbose_name_plural': 'Телефоны пользователей',
                'ordering': ['user', '-is_primary', 'phone_type'],
            },
        ),
        migrations.CreateModel(
            name='UserProductAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('access_class', models.CharField(choices=[('S', 'S — системный'), ('A', 'A — суперадмин'), ('B', 'B — высокий'), ('C', 'C — расширенный'), ('D', 'D — средний'), ('E', 'E — ограниченный'), ('F', 'F — минимальный служебный'), ('G', 'G — базовый пользователь')], default='G', max_length=1, verbose_name='Класс доступа')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('suspended', 'Приостановлен'), ('revoked', 'Отозван')], default='active', max_length=20, verbose_name='Статус доступа')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Доступ действует с')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='Доступ действует до')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_accesses', to='accounts.organization', verbose_name='Организация')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='accounts.product', verbose_name='Продукт')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_accesses', to='accounts.productrole', verbose_name='Роль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Доступ пользователя к продукту',
                'verbose_name_plural': 'Доступы пользователей к продуктам',
                'ordering': ['user', 'product', 'organization'],
            },
        ),
        migrations.AddConstraint(
            model_name='productpermission',
            constraint=models.UniqueConstraint(fields=('product', 'code'), name='unique_permission_code_per_product'),
        ),
        migrations.AddConstraint(
            model_name='productrole',
            constraint=models.UniqueConstraint(fields=('product', 'code'), name='unique_role_code_per_product'),
        ),
    ]
