# Generated by Django 5.2.14 on 2026-05-28 13:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название роли')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Роль в системе',
                'verbose_name_plural': 'Роли в системе',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['sort_order', 'code'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='admin_comment',
            field=models.TextField(blank=True, help_text='Виден только администраторам системы.', verbose_name='Комментарий администратора'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='public_comment',
            field=models.TextField(blank=True, help_text='Виден самому пользователю.', verbose_name='Комментарий для пользователя'),
        ),
        migrations.AddField(
            model_name='product',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='product_logos/', verbose_name='Логотип продукта'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_url',
            field=models.URLField(blank=True, verbose_name='Адрес продукта'),
        ),
        migrations.AddField(
            model_name='product',
            name='second_line',
            field=models.CharField(blank=True, max_length=255, verbose_name='Дополнительная строка'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='sort_order',
            field=models.PositiveIntegerField(default=100, verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='useremail',
            name='comment',
            field=models.CharField(blank=True, help_text='Например: рабочая почта, для уведомлений', max_length=255, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='userphone',
            name='comment',
            field=models.CharField(blank=True, help_text='Например: рабочий, звонить с 9 до 18', max_length=255, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='userphone',
            name='number',
            field=models.CharField(help_text='Только цифры без пробелов и тире. Например: 9036709699', max_length=15, validators=[django.core.validators.RegexValidator(message='Только цифры, от 5 до 15 символов.', regex='^\\d{5,15}$')], verbose_name='Номер'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='system_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.systemrole', verbose_name='Роль в системе'),
        ),
    ]
