# Generated by Django 5.2.15 on 2026-07-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_systemrole_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproductaccess',
            name='dominex_grant_id',
            field=models.PositiveIntegerField(blank=True, help_text='ProductAccessGrant.id из Dominex Core - если задан, эта запись является проекцией/кэшем, а не локально управляемой.', null=True, verbose_name='ID гранта в Dominex'),
        ),
        migrations.AddField(
            model_name='userproductaccess',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Синхронизировано из Dominex'),
        ),
    ]
