# Generated by Django 5.2.16 on 2026-07-13 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_authevent_product_config_synced'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalKeyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('wrapped_master_key', models.TextField(verbose_name='Зашифрованный мастер-ключ (base64)')),
                ('nonce', models.CharField(max_length=64, verbose_name='Nonce AEAD (base64)')),
                ('kdf_algorithm', models.CharField(default='argon2id', max_length=20, verbose_name='Алгоритм KDF')),
                ('kdf_salt', models.CharField(max_length=64, verbose_name='Соль KDF (base64)')),
                ('kdf_memory_kib', models.PositiveIntegerField(verbose_name='Argon2id: память (KiB)')),
                ('kdf_iterations', models.PositiveIntegerField(verbose_name='Argon2id: итерации')),
                ('kdf_parallelism', models.PositiveIntegerField(verbose_name='Argon2id: параллелизм')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_key_material', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Материал личного ключа',
                'verbose_name_plural': 'Материалы личных ключей',
            },
        ),
    ]
