# Generated by Django 5.2.16 on 2026-07-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_personalkeymaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authevent',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Успешный вход'), ('login_failed', 'Неуспешный вход'), ('logout', 'Выход'), ('key_login_success', 'Вход по ключу успешен'), ('key_login_failed', 'Вход по ключу неуспешен'), ('access_denied', 'Доступ запрещен'), ('access_granted', 'Доступ разрешен'), ('product_config_synced', 'Конфигурация продукта синхронизирована из Dominex'), ('personal_key_material_updated', 'Материал личного ключа обновлён (Biographia)')], max_length=50, verbose_name='Тип события'),
        ),
    ]
