# Generated by Django 5.2.16 on 2026-07-13 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_authevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalkeymaterial',
            name='label',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='personalkeymaterial',
            name='provider',
            field=models.CharField(choices=[('password', 'Пароль + seed-фраза'), ('webauthn_prf', 'WebAuthn PRF (токен/passkey)')], default='password', max_length=20, verbose_name='Способ разблокировки'),
        ),
        migrations.AlterField(
            model_name='personalkeymaterial',
            name='kdf_iterations',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Argon2id: итерации'),
        ),
        migrations.AlterField(
            model_name='personalkeymaterial',
            name='kdf_memory_kib',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Argon2id: память (KiB)'),
        ),
        migrations.AlterField(
            model_name='personalkeymaterial',
            name='kdf_parallelism',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Argon2id: параллелизм'),
        ),
        migrations.AlterField(
            model_name='personalkeymaterial',
            name='kdf_salt',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Соль KDF (base64)'),
        ),
        migrations.AlterField(
            model_name='personalkeymaterial',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_key_materials', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='WebAuthnCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('credential_id', models.CharField(max_length=255, unique=True, verbose_name='Credential ID (base64url)')),
                ('public_key', models.TextField(verbose_name='Публичный ключ (COSE, base64url)')),
                ('sign_count', models.PositiveIntegerField(default=0, verbose_name='Счётчик подписей')),
                ('transports', models.JSONField(blank=True, default=list, verbose_name='Транспорты')),
                ('label', models.CharField(blank=True, help_text='Например: YubiKey 5, Touch ID MacBook', max_length=255, verbose_name='Название')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее использование')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_credentials', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'WebAuthn-креденшл (Biographia)',
                'verbose_name_plural': 'WebAuthn-креденшлы (Biographia)',
            },
        ),
        migrations.AddField(
            model_name='personalkeymaterial',
            name='webauthn_credential',
            field=models.ForeignKey(blank=True, help_text='Заполнено только для provider=webauthn_prf.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key_materials', to='accounts.webauthncredential', verbose_name='Связанный WebAuthn-креденшл'),
        ),
    ]
