# Generated by Django 5.2.16 on 2026-07-17 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_personalkeymaterial_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('code', models.SlugField(help_text='Например: atb_portal', max_length=100, unique=True, verbose_name='Код клиента')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('client_secret_hash', models.CharField(max_length=128, verbose_name='SHA256 фингерпринт секрета')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее использование')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Машинный клиент (ServiceClient)',
                'verbose_name_plural': 'Машинные клиенты (ServiceClient)',
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='authevent',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Успешный вход'), ('login_failed', 'Неуспешный вход'), ('logout', 'Выход'), ('key_login_success', 'Вход по ключу успешен'), ('key_login_failed', 'Вход по ключу неуспешен'), ('access_denied', 'Доступ запрещен'), ('access_granted', 'Доступ разрешен'), ('product_config_synced', 'Конфигурация продукта синхронизирована из Dominex'), ('personal_key_material_updated', 'Материал личного ключа обновлён (Biographia)'), ('service_token_issued', 'Service-токен выдан'), ('service_token_denied', 'Service-токен отклонён')], max_length=50, verbose_name='Тип события'),
        ),
        migrations.CreateModel(
            name='ServiceClientGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('audience', models.SlugField(help_text='Например: dominex', max_length=100, verbose_name='Audience (целевой сервис)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('service_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='accounts.serviceclient', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Grant машинного клиента',
                'verbose_name_plural': "Grant'ы машинных клиентов",
                'ordering': ['service_client', 'audience'],
                'constraints': [models.UniqueConstraint(fields=('service_client', 'audience'), name='uq_service_client_grant')],
            },
        ),
    ]
