# Generated by Django 5.2.16 on 2026-07-22 10:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_serviceclient_alter_authevent_event_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('org_code', models.SlugField(max_length=100, verbose_name='Код организации')),
                ('target_host', models.CharField(max_length=255, verbose_name='SSH host VM')),
                ('target_port', models.PositiveIntegerField(default=22, verbose_name='SSH порт')),
                ('target_user', models.CharField(max_length=100, verbose_name='SSH пользователь')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('running', 'Выполняется'), ('success', 'Успешно'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('log', models.TextField(blank=True, verbose_name='Лог развёртывания')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deploy_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
                ('service_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deploy_jobs', to='accounts.serviceclient', verbose_name='Созданный клиент')),
            ],
            options={
                'verbose_name': 'Задача развёртывания портала',
                'verbose_name_plural': 'Задачи развёртывания порталов',
                'ordering': ['-created_at'],
            },
        ),
    ]
