# Generated by Django 5.2.17 on 2026-08-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_deployjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='repository_icons/', verbose_name='Значок')),
                ('download_url', models.URLField(help_text='Прямая ссылка на файл (например, https://biographia.ssod.pro/builds/latest.apk).', verbose_name='Ссылка на скачивание')),
                ('version_label', models.CharField(blank=True, help_text="Свободный текст, например 'build 7' - у разных продуктов разные схемы версионирования.", max_length=100, verbose_name='Версия/сборка')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Пункт репозитория',
                'verbose_name_plural': 'Репозиторий: пункты',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
