# Generated by Django 5.2.16 on 2026-08-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_repositoryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='infrastructure_access_override',
            field=models.BooleanField(default=False, help_text='Выдать плитку «Инфраструктура предприятия» вручную, даже если должность не входит в список INFRA_MANAGER_POSITIONS. Для случаев, когда должность руководителя названа нетипично.', verbose_name='Доступ к инфраструктуре предприятия'),
        ),
    ]
