"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = env("DJANGO_SECRET_KEY")

DEBUG = env.bool("DJANGO_DEBUG", default=False)

ALLOWED_HOSTS = env.list(
    "DJANGO_ALLOWED_HOSTS",
    default=["localhost", "127.0.0.1"],
)

CSRF_TRUSTED_ORIGINS = env.list(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    default=["https://auth.ssod.pro"],
)



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django_otp",
    "django_otp.plugins.otp_static",
    "django_otp_webauthn",
    # Приложение пользователей и авторизации ССОД.
    # Здесь позже будут ключи доступа, события входа, 2FA и роли.
    "accounts",
    "main",
    "control",

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    "django_otp.middleware.OTPMiddleware",
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("POSTGRES_DB"),
        "USER": env("POSTGRES_USER"),
        "PASSWORD": env("POSTGRES_PASSWORD"),
        "HOST": "ssod_auth_db",
        "PORT": "5432",
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = env("TIME_ZONE", default="Europe/Moscow")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# Папка, куда collectstatic собирает все static-файлы для production.
STATIC_ROOT = BASE_DIR / "staticfiles"

# Папки, где Django ищет наши собственные static-файлы проекта.
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
# Кастомная модель пользователя Auth Center.
# Важно: это надо указывать ДО первых рабочих миграций проекта.
# Мы используем accounts.CustomUser вместо стандартного auth.User,
# потому что нам нужны UUID, организация, должность, класс доступа
# и будущая интеграция с Dominex / FinSoft / ЛК.
AUTH_USER_MODEL = "accounts.CustomUser"
# Тип первичного ключа по умолчанию для моделей Django.
# BigAutoField нормален для растущего проекта и убирает предупреждения W042.
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ---------------------------------------------------------------------
# Email / SMTP
# ---------------------------------------------------------------------
# Используется для отправки пользователям:
# - уведомлений о создании учетной записи;
# - временных паролей;
# - уведомлений о блокировке;
# - уведомлений о выпуске/отзыве ключа доступа ССОД.

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = env("EMAIL_HOST")
EMAIL_PORT = env.int("EMAIL_PORT", default=465)

EMAIL_USE_SSL = env.bool("EMAIL_USE_SSL", default=True)
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=False)

EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")

DEFAULT_FROM_EMAIL = env(
    "DEFAULT_FROM_EMAIL",
    default="ССОД Auth Center <auth@ssod.pro>",
)

SERVER_EMAIL = env(
    "SERVER_EMAIL",
    default="auth@ssod.pro",
)
# ---------------------------------------------------------------------
# Auth redirects
# ---------------------------------------------------------------------
# Обычных пользователей отправляем не в Django Admin,
# а в пользовательский вход Auth Center.
LOGIN_URL = "/account/login/"

# После успешного входа пользователь попадает в ЛК.
LOGIN_REDIRECT_URL = "/account/"

# После выхода возвращаем на главную Auth Center.
LOGOUT_REDIRECT_URL = "/"

# ---------------------------------------------------------------------
# Passkeys / WebAuthn
# ---------------------------------------------------------------------

OTP_WEBAUTHN_RP_NAME = "ССОД Auth Center"
OTP_WEBAUTHN_RP_ID = "auth.ssod.pro"

OTP_WEBAUTHN_ALLOWED_ORIGINS = [
    "https://auth.ssod.pro",
]

WEBAUTHN_ALLOWED_ORIGINS = [
    "https://auth.ssod.pro",
]

OTP_WEBAUTHN_ALLOW_PASSWORDLESS_LOGIN = True


LOGIN_URL = "/account/login/"
LOGIN_REDIRECT_URL = "/account/"
LOGOUT_REDIRECT_URL = "/"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "django_otp_webauthn.backends.WebAuthnBackend",
]
