"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = env("DJANGO_SECRET_KEY")

DEBUG = env.bool("DJANGO_DEBUG", default=False)

ALLOWED_HOSTS = env.list(
    "DJANGO_ALLOWED_HOSTS",
    default=["localhost", "127.0.0.1"],
)

# Docker-internal hostname Dominex uses to call the admin write-bridge
# directly (accounts/api.py::admin_update_product). Not the plain service
# name "ssod_auth_web" - Django's Host-header validation (RFC 1034/1035)
# rejects underscores outright regardless of ALLOWED_HOSTS, so
# docker-compose.yml gives this service a hyphenated network alias
# instead. Internal-only (not reachable from outside the docker network),
# fixed in every environment using this compose file, so always safe to
# allow regardless of what DJANGO_ALLOWED_HOSTS is set to.
if "ssod-auth-internal" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append("ssod-auth-internal")

CSRF_TRUSTED_ORIGINS = env.list(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    default=["https://auth.ssod.pro"],
)



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django_otp",
    "django_otp.plugins.otp_static",
    "django_otp_webauthn",
    # Приложение пользователей и авторизации ССОД.
    # Здесь позже будут ключи доступа, события входа, 2FA и роли.
    "accounts",
    "main",
    "control",

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    "django_otp.middleware.OTPMiddleware",
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("POSTGRES_DB"),
        "USER": env("POSTGRES_USER"),
        "PASSWORD": env("POSTGRES_PASSWORD"),
        "HOST": "ssod_auth_db",
        "PORT": "5432",
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = env("TIME_ZONE", default="Europe/Moscow")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# Папка, куда collectstatic собирает все static-файлы для production.
STATIC_ROOT = BASE_DIR / "staticfiles"

# Папки, где Django ищет наши собственные static-файлы проекта.
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# ---------------------------------------------------------------------
# Media files (avatars, uploads)
# ---------------------------------------------------------------------
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "mediafiles"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
# Кастомная модель пользователя Auth Center.
# Важно: это надо указывать ДО первых рабочих миграций проекта.
# Мы используем accounts.CustomUser вместо стандартного auth.User,
# потому что нам нужны UUID, организация, должность, класс доступа
# и будущая интеграция с Dominex / FinSoft / ЛК.
AUTH_USER_MODEL = "accounts.CustomUser"
# Тип первичного ключа по умолчанию для моделей Django.
# BigAutoField нормален для растущего проекта и убирает предупреждения W042.
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ---------------------------------------------------------------------
# Email / SMTP
# ---------------------------------------------------------------------
# Используется для отправки пользователям:
# - уведомлений о создании учетной записи;
# - временных паролей;
# - уведомлений о блокировке;
# - уведомлений о выпуске/отзыве ключа доступа ССОД.

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = env("EMAIL_HOST")
EMAIL_PORT = env.int("EMAIL_PORT", default=465)

EMAIL_USE_SSL = env.bool("EMAIL_USE_SSL", default=True)
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=False)

EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")

DEFAULT_FROM_EMAIL = env(
    "DEFAULT_FROM_EMAIL",
    default="ССОД Auth Center <auth@ssod.pro>",
)

SERVER_EMAIL = env(
    "SERVER_EMAIL",
    default="auth@ssod.pro",
)
# ---------------------------------------------------------------------
# Auth redirects
# ---------------------------------------------------------------------
# Обычных пользователей отправляем не в Django Admin,
# а в пользовательский вход Auth Center.
LOGIN_URL = "/account/login/"

# После успешного входа пользователь попадает в ЛК.
LOGIN_REDIRECT_URL = "/account/"

# После выхода возвращаем на главную Auth Center.
LOGOUT_REDIRECT_URL = "/"

# ---------------------------------------------------------------------
# Passkeys / WebAuthn
# ---------------------------------------------------------------------

OTP_WEBAUTHN_RP_NAME = "ССОД Auth Center"
OTP_WEBAUTHN_RP_ID = "auth.ssod.pro"

OTP_WEBAUTHN_ALLOWED_ORIGINS = [
    "https://auth.ssod.pro",
]

WEBAUTHN_ALLOWED_ORIGINS = [
    "https://auth.ssod.pro",
]

OTP_WEBAUTHN_ALLOW_PASSWORDLESS_LOGIN = True


LOGIN_URL = "/account/login/"
LOGIN_REDIRECT_URL = "/account/"
LOGOUT_REDIRECT_URL = "/"

# When True (default), Dominex is the sole store of login credentials -
# DominexCredentialBackend replaces the local password check entirely.
# Flip to False (+ restart) as a break-glass rollback: re-adds ModelBackend,
# which still works for any account with a real local hash (notably the
# Django superuser(s) created before this switch - their local password is
# deliberately left untouched, see the 0006 data migration).
DOMINEX_CREDENTIAL_BACKEND_ENABLED = env.bool("DOMINEX_CREDENTIAL_BACKEND_ENABLED", default=True)

AUTHENTICATION_BACKENDS = [
    "accounts.auth_backends.DominexCredentialBackend",
    "django_otp_webauthn.backends.WebAuthnBackend",
]
if not DOMINEX_CREDENTIAL_BACKEND_ENABLED:
    AUTHENTICATION_BACKENDS.insert(1, "django.contrib.auth.backends.ModelBackend")

# Dominex Core console location. In production this should point to the public Dominex Core URL.
DOMINEX_CORE_CONSOLE_URL = env("DOMINEX_CORE_CONSOLE_URL", default="http://127.0.0.1:5006/core/console/")

# Dominex Core identity/access projection API (see dominex/docs/module-interactions.md).
# Base URL only (no trailing /api/v1) - accounts/services/dominex_client.py appends the path.
# Key must match Dominex's DOMINEX_INTEGRATION_API_KEY.
DOMINEX_API_BASE_URL = env("DOMINEX_API_BASE_URL", default="http://dominex_app:5000")
DOMINEX_API_KEY = env("DOMINEX_API_KEY", default="dev-integration-key-change-me")

# When True, Dominex is the sole source of truth for organization/position/
# access_class/product access - local admin/control UI stops allowing direct
# edits of those fields (see dominex/docs/module-interactions.md "Connected
# Dominex Mode"). Flip to False as an emergency/local-mode rollback lever.
DOMINEX_CONNECTED_MODE = env.bool("DOMINEX_CONNECTED_MODE", default=True)

# Shared secret for verifying/issuing SSO tickets exchanged with Dominex
# (see dominex/docs/module-interactions.md "Credential, Session, Token and
# API Key Lifecycle"). Must match Dominex's SSO_TICKET_SECRET.
SSO_TICKET_SECRET = env("SSO_TICKET_SECRET", default="dev-sso-ticket-secret-change-me")

# Write-through admin bridge: Dominex's "Настройки -> Продукты и подключаемые
# модули" screen pushes Product field changes (sso_enabled etc.) here via
# accounts.api.admin_update_product - the one server-to-server call that
# goes Dominex -> ssod_auth instead of the usual other way round (see
# biographia TZ section 13). Own secret, not reused from DOMINEX_API_KEY
# or SSO_TICKET_SECRET - same "one secret per consumer/direction" rule
# this whole mechanism exists to enforce.
DOMINEX_ADMIN_API_KEY = env("DOMINEX_ADMIN_API_KEY", default="dev-admin-bridge-key-change-me")

# Personal-zone key registry write channel: Biographia's backend stores/
# fetches a user's wrapped master key here (biographia TZ section 4) -
# never the plaintext key, password, or seed phrase, only ciphertext +
# public KDF params. New direction again (Biographia -> ssod_auth, not
# the usual other way), own secret again - same rule as
# DOMINEX_ADMIN_API_KEY above, not reused from it or from anything else.
BIOGRAPHIA_KEY_API_KEY = env("BIOGRAPHIA_KEY_API_KEY", default="dev-biographia-key-api-change-me")
